/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import entity.OrdemServico;
import java.util.List;
import javax.swing.JOptionPane;
import service.SistemaOsService;

/**
 *
 * @author admin
 */
public class SistemaOsController extends javax.swing.JFrame {

    SistemaOsService sistemaOsService = new SistemaOsService();

    /**
     * Creates new form SistemaOsController
     */
    public SistemaOsController() {
        initComponents();
        configurarLarguraColunas();
    }

    private void configurarLarguraColunas() {
        jtOs.getColumnModel().getColumn(0).setPreferredWidth(jtOs.getWidth() / 20);
        jtOs.getColumnModel().getColumn(1).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(2).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(3).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(4).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(5).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(6).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(7).setPreferredWidth(jtOs.getWidth() / 6);
        jtOs.getColumnModel().getColumn(8).setPreferredWidth(jtOs.getWidth() / 6);
        jtOs.getColumnModel().getColumn(9).setPreferredWidth(jtOs.getWidth() / 15);
    }

    public void limparTabela() {

        for (int i = 0; i < jtOs.getRowCount(); i++) {
            jtOs.setValueAt(null, i, 0);
            jtOs.setValueAt(null, i, 1);
            jtOs.setValueAt(null, i, 2);
            jtOs.setValueAt(null, i, 3);
            jtOs.setValueAt(null, i, 4);
            jtOs.setValueAt(null, i, 5);
        }
    }

    private void preencheTabela(List<OrdemServico> ordensServico) {
        int i = 0;
        for (OrdemServico os : ordensServico) {
            int k = 0;
            jtOs.setValueAt(os.getId(), i, k++);
            jtOs.setValueAt(os.getCliente(), i, k++);
            jtOs.setValueAt(os.getAparelho(), i, k++);
            jtOs.setValueAt(os.getTecnico(), i, k++);
            jtOs.setValueAt(os.getData_abertura(), i, k++);
            jtOs.setValueAt(os.getData_fechamento(), i, k++);
            jtOs.setValueAt(os.getStatus(), i, k++);
            jtOs.setValueAt(os.getDescricao_problema(), i, k++);
            jtOs.setValueAt(os.getSolucao(), i, k++);
            jtOs.setValueAt(os.getCusto_total(), i, k++);

            i++;
        }
    }

    public boolean linhaEstaSelecionada() {
        return jtOs.getSelectedRow() > -1;
    }

//    public OrdemServico lerDadosDaTabela() {
//        OrdemServico osSelecionada = new OrdemServico();
//        int linhaSelecionada = jtOs.getSelectedRow();
//        osSelecionada.setId(Integer.parseInt(jtOs.getValueAt(linhaSelecionada, 0).toString()));
//        osSelecionada.setCliente(Integer.parseInt(jtOs.getValueAt(linhaSelecionada, 1).toString()));
//        osSelecionada.setId_aparelho(Integer.parseInt(jtOs.getValueAt(linhaSelecionada, 2).toString()));
//        osSelecionada.setId_tecnico(Integer.parseInt(jtOs.getValueAt(linhaSelecionada, 3).toString()));
//        osSelecionada.setData_abertura(jtOs.getValueAt(linhaSelecionada, 4).toString());
//        osSelecionada.setData_fechamento(jtOs.getValueAt(linhaSelecionada, 5).toString());
//        osSelecionada.setStatus(jtOs.getValueAt(linhaSelecionada, 6).toString());
//        osSelecionada.setDescricao_problema(jtOs.getValueAt(linhaSelecionada, 7).toString());
//        osSelecionada.setSolucao(jtOs.getValueAt(linhaSelecionada, 8).toString());
//        osSelecionada.setCusto_total(Double.parseDouble(jtOs.getValueAt(linhaSelecionada, 9).toString()));
//        return osSelecionada;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOs = new javax.swing.JTable();
        jbCriarNovaOs = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordens de Servico");

        jtOs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Id Cliente", "Id Aparelho", "Id Técnico", "Data da Abertura", "Data do Fechamento", "Status", "Descrição do Problema", "Solução", "Custo Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtOs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jtOs);

        jbCriarNovaOs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbCriarNovaOs.setText("Criar");
        jbCriarNovaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarNovaOsActionPerformed(evt);
            }
        });

        jbAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jbCriarNovaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCriarNovaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCriarNovaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarNovaOsActionPerformed
        new OrdemServicoController().setVisible(true);
    }//GEN-LAST:event_jbCriarNovaOsActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        boolean osExcluida = false;
        int linhaSelecionada = jtOs.getSelectedRow();
        try {
            if (linhaEstaSelecionada()) {
                osExcluida = sistemaOsService.excluirOs(Integer.parseInt(jtOs.getValueAt(linhaSelecionada, 0).toString()));
            } else {
                JOptionPane.showMessageDialog(null, "Para realizar essa ação, selecione uma ordem de serviço");
            }
            if (osExcluida) {
                JOptionPane.showMessageDialog(null, "Ordem de serviço excluída com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro qualquer no banco!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (linhaEstaSelecionada()) {
//            new OrdemServicoController(lerDadosDaTabela()).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Para realizar essa ação, selecione um contato");
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaOsController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbCriarNovaOs;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JTable jtOs;
    // End of variables declaration//GEN-END:variables
}
