/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import entity.SistemaOs;
import java.util.List;

/**
 *
 * @author admin
 */
public class SistemaOsController extends javax.swing.JFrame {

    /**
     * Creates new form SistemaOsController
     */
    public SistemaOsController() {
        initComponents();
        configurarLarguraColunas();
    }
    
    private void configurarLarguraColunas() {
        jtOs.getColumnModel().getColumn(0).setPreferredWidth(jtOs.getWidth() / 20);
        jtOs.getColumnModel().getColumn(1).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(2).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(3).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(4).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(5).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(6).setPreferredWidth(jtOs.getWidth() / 15);
        jtOs.getColumnModel().getColumn(7).setPreferredWidth(jtOs.getWidth() / 6);
        jtOs.getColumnModel().getColumn(8).setPreferredWidth(jtOs.getWidth() / 6);
        jtOs.getColumnModel().getColumn(9).setPreferredWidth(jtOs.getWidth() / 15);
    }
    public void limparTabela() {

        for (int i = 0; i < jtOs.getRowCount(); i++) {
            jtOs.setValueAt(null, i, 0);
            jtOs.setValueAt(null, i, 1);
            jtOs.setValueAt(null, i, 2);
            jtOs.setValueAt(null, i, 3);
            jtOs.setValueAt(null, i, 4);
            jtOs.setValueAt(null, i, 5);
        }
    }

    private void preencheTabela(List<SistemaOs> ordensServico) {
        int i = 0;
        for (SistemaOs os : ordensServico) {
            int k = 0;
            jtOs.setValueAt(os.getId(), i, k++);
            jtOs.setValueAt(os.getId_cliente(), i, k++);
            jtOs.setValueAt(os.getId_aparelho(), i, k++);
            jtOs.setValueAt(os.getId_tecnico(), i, k++);
            jtOs.setValueAt(os.getData_abertura(), i, k++);
            jtOs.setValueAt(os.getData_fechamento(), i, k++);
            jtOs.setValueAt(os.getStatus(), i, k++);
            jtOs.setValueAt(os.getDescricao_problema(), i, k++);
            jtOs.setValueAt(os.getSolucao(), i, k++);
            jtOs.setValueAt(os.getCusto_total(), i, k++);

            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordens de Servico");

        jtOs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Id Cliente", "Id Aparelho", "Id Técnico", "Data da Abertura", "Data do Fechamento", "Status", "Descrição do Problema", "Solução", "Custo Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtOs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jtOs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addGap(303, 303, 303))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaOsController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaOsController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtOs;
    // End of variables declaration//GEN-END:variables
}
